### ISSUE TITLE
Add support for OpenTelemetry Java Instrumentation 2.0.0+

### ISSUE THREAD

**Issue by ThomasVitale** [paketo-buildpacks/opentelemetry#113]
## Describe the Enhancement
The new major release train of OpenTelemetry Java Instrumentation introduces several breaking change. This enhancement is to prepare a new major release of this buildpack to add support for it, and handle carefully the release process to avoid affecting existing users of this buildpack.

Release notes: https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v2.0.0

## Context
See: https://github.com/paketo-buildpacks/opentelemetry/pull/112

**Comment by ThomasVitale** [comment]
@anthonydahanne yeah, it seems a good time for that. I'll start working on this and submit a PR soon

**Comment by tudburley** [comment]
Hi, is there any time schedule when the update to OpenTelemetry 2.4 will be done? As mentioned [here](https://github.com/paketo-buildpacks/opentelemetry/pull/112#issuecomment-1909866896), OTel 1.32.x is only supported until May.

**Comment by ThomasVitale** [comment]
@tudburley As soon as this PR is merged, we should be able to cut a new release: https://github.com/paketo-buildpacks/opentelemetry/pull/132 @dmikusa what do you think?

**Comment by StefanLobbenmeierObjego** [comment]
FYI there is a slight breaking change in opentelemetry v2, because it changed from http to grpc by default. We export to tempo, so it was just a matter of replacing the  OTEL_EXPORTER_OTLP_ENDPOINT port from 4317 to 4318
