### ISSUE TITLE
Unable to build with java maven app

### ISSUE THREAD

**Issue by makeavish** [paketo-buildpacks/opentelemetry#17]
## Expected Behavior
It should build successfully

## Current Behavior
Build failing at detect step:

```
======== Error: paketo-buildpacks/opentelemetry@0.0.1 ========
fork/exec /cnb/buildpacks/paketo-buildpacks_opentelemetry/0.0.1/bin/detect: no such file or directory
....
...
ERROR: No buildpack groups passed detection.
ERROR: failed to detect: buildpack(s) failed with err
ERROR: failed to build: executing lifecycle: failed with status code: 21
```

## Steps to Reproduce

1. I am trying to instrument Java Maven Sample Application: https://github.com/paketo-buildpacks/samples/tree/main/java/maven
2. Below is the command which I am running after opening opentelemetry buildpack dir
``` pack build paketo-demo-app \
  --path /Users/makeavish/samples/java/maven \
  --buildpack paketo-buildpacks/java \
  --buildpack . \
  --builder paketobuildpacks/builder:base \
  --verbose --trust-builder \
  -e BP_JVM_VERSION=17 -e BP_OPENTELEMETRY_ENABLED=true
```

**Comment by ThomasVitale** [comment]
@makeavish thanks for reporting the issue. Could you try from running the build from this branch? https://github.com/paketo-buildpacks/opentelemetry/tree/config-binding

**Comment by makeavish** [comment]
@ThomasVitale Same errors.
```
======== Error: paketo-buildpacks/opentelemetry@0.0.1 ========
fork/exec /cnb/buildpacks/paketo-buildpacks_opentelemetry/0.0.1/bin/detect: no such file or directory
```

**Comment by dmikusa** [comment]
You can't point `-b` at the buildpack source code. The buildpack is written in Go and needs to be compiled. See https://github.com/paketo-buildpacks/opentelemetry/issues/9#issuecomment-1246787125 for instructions.

**Comment by makeavish** [comment]
@dmikusa It proceeded, thanks!
But it's failing with this error:
```
  https://github.com/paketo-buildpacks/opentelemetry
  OpenTelemetry Java Agent 1.18.0: Contributing to layer
    Downloading from https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.18.0/opentelemetry-javaagent.jar
    Verifying checksum
    Copying to /layers/paketo-buildpacks_opentelemetry/opentelemetry-java
    Writing env.launch/JAVA_TOOL_OPTIONS.append
    Writing env.launch/JAVA_TOOL_OPTIONS.delim
    Writing env.launch/OTEL_JAVAAGENT_ENABLED.default
    Writing env.launch/OTEL_METRICS_EXPORTER.default
  Launch Helper: Contributing to layer
unable to invoke layer creator
unable to open /cnb/buildpacks/paketo-buildpacks_opentelemetry/0.0.1/bin/helper
open /cnb/buildpacks/paketo-buildpacks_opentelemetry/0.0.1/bin/helper: no such file or directory
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 51
```

**Comment by ThomasVitale** [comment]
@makeavish I have updated the documentation with the missing step: https://github.com/paketo-buildpacks/opentelemetry/blob/config-binding/README.md#testing Before running the `pack` command, you can compile the Buildpack using the provided script. That will solve the missing "helper" problem.

`scripts/build.sh`

**Comment by makeavish** [comment]
Was able to build and run the app. Thanks @ThomasVitale
But I am not seeing any traces getting generated, also tried printing traces on console by using otel debug env variable. I used below command to run:

```
docker run -d -p 8080:8080 -e PORT=8080 -e OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317 -e OTEL_RESOURCE_ATTRIBUTES=service.name=javaApp -e OTEL_LOG_LEVEL=debug paketo-demo-app
```

**Comment by ThomasVitale** [comment]
@makeavish The agent is included but disabled by default. You can enable it by adding the following to your docker command:

`-e OTEL_JAVAAGENT_ENABLED=true`

**Comment by makeavish** [comment]
@ThomasVitale It worked finally!
I think we should update README on setup.
Should I create a PR?
