### ISSUE TITLE
unable to open /cnb/buildpacks/paketo-buildpacks_opentelemetry/0.2.0/bin/helper

### ISSUE THREAD

**Issue by talberadt** [paketo-buildpacks/opentelemetry#31]
I am trying to use this buildpack with spring's bootBuildImage task.
I am using the default builder (paketobuildpacks/builder:base) along with the following buildpacks:
    buildpacks = ['paketo-buildpacks/java', 'gcr.io/paketo-buildpacks/opentelemetry']
and the following env vars:
    environment = ["BP_OPENTELEMETRY_ENABLED" : "true"]

I am getting this error from bootBulldImage:
```
[creator]     Running build for buildpack paketo-buildpacks/opentelemetry@0.2.0
    [creator]     Looking up buildpack
    [creator]     Finding plan
    [creator]     Creating plan directory
    [creator]     Preparing paths
    [creator]     Running build command
    [creator]     
    [creator]     Paketo OpenTelemetry Buildpack 0.2.0
    [creator]       https://github.com/paketo-buildpacks/opentelemetry
    [creator]       OpenTelemetry Java Agent 1.19.1: Contributing to layer
    [creator]         Downloading from https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.19.1/opentelemetry-javaagent.jar
    [creator]         Verifying checksum
    [creator]         Copying to /layers/paketo-buildpacks_opentelemetry/opentelemetry-java
    [creator]         Writing env.launch/JAVA_TOOL_OPTIONS.append
    [creator]         Writing env.launch/JAVA_TOOL_OPTIONS.delim
    [creator]         Writing env.launch/OTEL_JAVAAGENT_ENABLED.default
    [creator]         Writing env.launch/OTEL_METRICS_EXPORTER.default
    [creator]       Launch Helper: Contributing to layer
    [creator]     unable to invoke layer creator
    [creator]     unable to open /cnb/buildpacks/paketo-buildpacks_opentelemetry/0.2.0/bin/helper
    [creator]     open /cnb/buildpacks/paketo-buildpacks_opentelemetry/0.2.0/bin/helper: no such file or directory
    [creator]     ERROR: failed to build: exit status 1
```

And the task fails without building the image.

## Expected Behavior
File should be found and image should be created.

## Current Behavior
as listed above.

## Steps to Reproduce
```
bootBuildImage {
    imageName = ".."
    runImage = ".."
    environment = ["BP_OPENTELEMETRY_ENABLED" : "true"]
    buildpacks = ['paketo-buildpacks/java', 'gcr.io/paketo-buildpacks/opentelemetry']
    verboseLogging = true
}
```

## Motivations
This buildpack fits perfectly with my needs to add otel java agent to my images.
I would love to use it and I can't figure out what's wrong.

Any help will be appreciated!

**Comment by dmikusa** [comment]
Apologizes. I'm not quite sure how that has slipped through testing. The helper binary was not being packaged with the buildpack. I've got a PR open to fix this. When that's merged, I'll cut another beta release.

Thanks for testing & for the feedback!

**Comment by dmikusa** [comment]
@talberadt  v0.2.1 is publishing now. Should be ready in a few mins. If you could give that a try, I think it should get you past this error. Thanks

**Comment by talberadt** [comment]
@dmikusa Works like a charm.
Thanks for your work and quick response!
