### ISSUE TITLE
Is this available, yet?

### ISSUE THREAD

**Issue by franktroia** [paketo-buildpacks/opentelemetry#9]
Hi All,

I came across this buildpack while trying to integrate OpenTelemetry with a spring boot app. This buildpack is exactly what I'm looking for, but I think it is not available yet. Can you confirm?

I ask because I do not see the buildpack published to docker hub (I hope I have not missed it).

Thanks in advance!

**Comment by dmikusa** [comment]
Correct. It's still in development. I don't think we're far off, but I believe @ThomasVitale might have a few more things he wanted to do before we release. I'll let him speak to that more.

**Comment by margic** [comment]
Is there a way to test this in advance of release?

**Comment by ThomasVitale** [comment]
@margic you can find instructions on how to test it locally with your own applications in the README file here: https://github.com/paketo-buildpacks/opentelemetry/blob/main/README.md

Feel free to share feedback and ideas to improve it, thank you!

**Comment by dmikusa** [comment]
You can run `go install -ldflags="-s -w" github.com/paketo-buildpacks/libpak/cmd/create-package@latest` to install `create-package`, then run `create-package --source . --destination ./out --version "0.0.1-dev"` from the buildpack directory. This will create a compiled version of the buildpack in the `./out` directory. You can point `pack` to that with `pack build <all your normal args> -b ./out`.

**Comment by PriyankPa** [comment]
Is there a way I can try this with kpack? I have it all setup but was wondering why the agent isn't getting included.

**Comment by dmikusa** [comment]
You need an image to test it. You can build yourself an image, but it's a little tricky. I just built an image and pushed it up to my personal docker hub, if you'd like to try it out, that's the easiest for now.

https://hub.docker.com/r/dmikusa/paketo-buildpacks-opentelemetry

Run `pack build <app-img> -b paketo-buildpacks/java -b docker.io/dmikusa/paketo-buildpacks-opentelemetry -e BP_OPENTELEMETRY_ENABLED=true`.

**Comment by PriyankPa** [comment]
Thanks, for creating the container. I want to use it in our pipeline which means, I am only allowed to use official releases. Any idea when this will be Generally Available?

**Comment by ThomasVitale** [comment]
@dmikusa I think we can start preparing the first release. I've just opened a PR with the remaining changes: https://github.com/paketo-buildpacks/opentelemetry/pull/23

**Comment by ThomasVitale** [comment]
@PriyankPa the first release is now out: https://github.com/paketo-buildpacks/opentelemetry/releases/tag/v0.1.0

**Comment by dmikusa** [comment]
Hi all! I cut a 0.2.0 release for everyone to try (consider it a RC). If you see any issues please report them. If no issues are reported, we'll bump this to 1.0 shortly.

**Comment by ThomasVitale** [comment]
Version 1.0.0 has been released 2 weeks ago: https://github.com/paketo-buildpacks/opentelemetry/releases/tag/v1.0.0 We should be able to close this issue now.
